-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 21:41:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDStud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDStud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDStud` DEFAULT CHARACTER SET utf8 ;
USE `BDStud` ;

-- -----------------------------------------------------
-- Table `BDStud`.`StatementInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDStud`.`StatementInfo` (
  `IDWe` INT NOT NULL,
  `IDStatement` INT NOT NULL,
  `Nzach` INT NULL,
  `Lecture1` INT NULL,
  `Practice1` INT NULL,
  `Lab1` INT NULL,
  `Skip1` INT NULL,
  `Result1` INT NULL,
  `Lecture2` INT NULL,
  `Practice2` INT NULL,
  `Lab2` INT NULL,
  `Skip2` INT NULL,
  `Result2` INT NULL,
  `Offset` INT NULL,
  `AllResult` INT NULL,
  `RatingIn5Ball` INT NULL,
  `StatementInfocol` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDStud`.`We`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDStud`.`We` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nzach` INT NOT NULL,
  `Fam` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `IDWe`
    FOREIGN KEY (`ID`)
    REFERENCES `BDStud`.`StatementInfo` (`IDWe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDStud`.`StatementName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDStud`.`StatementName` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDStatementSite` INT NOT NULL,
  `StatementName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDStatement_idx` (`IDStatementSite` ASC) VISIBLE,
  CONSTRAINT `IDStatement`
    FOREIGN KEY (`IDStatementSite`)
    REFERENCES `BDStud`.`StatementInfo` (`IDStatement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
